version: '3.7'
services:
  mysql:
    image: "mysql:5.7"
    ports:
      - ${MYSQL_PORT}:3306
    env_file: 
      - .env
    networks:
      - otasoft-catalog-network

networks: 
  otasoft-catalog-network:
    driver: bridge