version: '3.7'
services:
  mysql:
    image: "mysql:5.7"
    ports:
      - ${MYSQL_PORT}:3306
    env_file: 
      - .env
    networks:
      - db

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    environment:
      - node.name=es01
      - cluster.name=${ELASTICSEARCH_CLUSTER_NAME}
      - network.host=${ELASTICSEARCH_NETWORK_HOST}
      - http.port=${ELASTICSEARCH_PORT}
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    networks:
      - elastic
      - proxy

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    environment:
      - node.name=es02
      - cluster.name=${ELASTICSEARCH_CLUSTER_NAME}
      - network.host=${ELASTICSEARCH_NETWORK_HOST}
      - http.port=${ELASTICSEARCH_PORT}
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data02:/usr/share/elasticsearch/data
    networks:
      - elastic

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    environment:
      - node.name=es03
      - cluster.name=${ELASTICSEARCH_CLUSTER_NAME}
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data03:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    environment:
      SERVER_NAME: ${KIBANA_SERVER_NAME}
      ELASTICSEARCH_URL: http://elasticsearch:${ELASTICSEARCH_PORT}/
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      - elastic
      - proxy

  nginx:
    image: nginx:alpine
    ports:
        - ${NGINX_PORT}:80
    volumes:
        - ${PWD}/nginx/:/etc/nginx/conf.d/
        - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    ulimits:
      nproc: 65535
    networks:
      - proxy

networks: 
  elastic:
    driver: bridge
  proxy:
    driver: bridge
  db: 
    driver: bridge

volumes:
  es-data01:
    driver: local
  es-data02:
    driver: local
  es-data03:
    driver: local
