version: '3.7'
services:
  mysql:
    image: "mysql:5.7"
    ports:
      - ${MYSQL_PORT}:3306
    env_file: 
      - .env
    networks:
      - otasoft-catalog-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    environment:
      - node.name=es01
      - cluster.name=${ELASTICSEARCH_CLUSTER_NAME}
      - network.host=${ELASTICSEARCH_NETWORK_HOST}
      - http.port=${ELASTICSEARCH_PORT}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    networks:
      - otasoft-catalog-network
      - ingress

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    environment:
      SERVER_NAME: ${KIBANA_SERVER_NAME}
      ELASTICSEARCH_URL: http://elasticsearch:${ELASTICSEARCH_PORT}/
    ports:
      - ${KIBANA_PORT}:5601
    networks:
      - otasoft-catalog-network
      - ingress

  nginx:
    image: nginx:alpine
    ports:
        - ${NGINX_PORT}:80
    volumes:
        - ${PWD}/nginx/:/etc/nginx/conf.d/
        - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    ulimits:
      nproc: 65535
    networks:
      - ingress

networks: 
  otasoft-catalog-network:
    driver: bridge
  ingress:
    driver: bridge

volumes:
  es-data:
